fix /Users/ivan/Documents/GitHub/spicedb/internal/graph/errors.go:69:43: cannot use RelationNotFoundError{} (value of type RelationNotFoundError) as sharederrors.UnknownRelationError value in variable declaration: RelationNotFoundError does not implement sharederrors.UnknownRelationError (missing method NotFoundRelationName)