fix /Users/ivan/Documents/GitHub/spicedb/internal/services/shared/interceptor.go:44:45: cannot use WithUnaryServiceSpecificInterceptor{} (value of type WithUnaryServiceSpecificInterceptor) as servicespecific.ExtraUnaryInterceptor value in variable declaration: WithUnaryServiceSpecificInterceptor does not implement servicespecific.ExtraUnaryInterceptor (missing method UnaryInterceptor)