fix(CI): CLA GitHub Action permissions
The cla-assistant GitHub Action is currently failing with:
```
Error: Could not update the JSON file: Error occured when creating a pull request comment: Resource not accessible by integration
```
I suspect this was caused by a recent change to the workflow's
permissiosn in https://github.com/authzed/spicedb/pull/2353.

This should fix the issue, according to the workflow's
upstream's upstream
https://github.com/contributor-assistant/github-action?tab=readme-ov-file#configure-contributor-license-agreement-within-two-minutes.

Signed-off-by: squat <lserven@gmail.com>